#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def check_mk_version_valid_info(info):
    return info is not None and len(info) == 1 and len(info[0]) == 3


def inventory_check_mk_version(info):
    if check_mk_version_valid_info(info):
        yield None, {}


def check_check_mk_version(_no_item, _no_params, info):
    if not check_mk_version_valid_info(info):
        return

    arm_version, latest_version, up_to_date = info[0]
    state = int(up_to_date)
    details = 'Check_MK %s is the latest version' % arm_version
    if state > 0:
        details = 'Check_MK %s is out of date, current version: %s' % (arm_version, latest_version)

    return state, details


check_info['check_mk_version'] = {
    'inventory_function'      : inventory_check_mk_version,
    'check_function'          : check_check_mk_version,
    'service_description'     : 'Check_MK Version',
}
