#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

import json
import requests


access_token = '<your-github-personal-access-token>'
version_of_interest = '1.6.0'


def get_arm_version():
    response = requests.get('https://api.github.com/repos/chrisss404/check-mk-arm/releases/latest')
    last_release = json.loads(response.text)
    return last_release['tag_name']


def get_checkmk_version():
    headers = {"Authorization": "token " + access_token}
    query = '''
        query($repo_owner: String!, $repo_name: String!) {
          repository(owner: $repo_owner, name: $repo_name) {
            refs(refPrefix: "refs/tags/", last: 4, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
              edges {
                node {
                  name
                }
              }
            }
          }
        }'''
    variables = {
        "repo_owner": "tribe29",
        "repo_name": "checkmk"
    }

    response = requests.post('https://api.github.com/graphql', json={'query': query, 'variables': variables}, headers=headers)
    if response.status_code == 200:
        try:
            edges = reversed(json.loads(response.text)['data']['repository']['refs']['edges'])
            for edge in edges:
                tag_name = edge['node']['name']
                if version_of_interest in tag_name:
                    return tag_name.lstrip('v')
        except:
            pass
    return 'unknown'


arm_version = get_arm_version()
latest_version = get_checkmk_version()
print('<<<check_mk_version>>>')
print('%s %s %s' % (arm_version, latest_version, '0' if arm_version == latest_version else '1'))
